=== iggor1995/Airlines/src/main/java/xmlpack/xml.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.w3schools.com"
           xmlns="https://www.w3schools.com"
           elementFormDefault="qualified">

        <xs:element name = "aircompany">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name = "cargoPlane" type = "cargoPlane" minOccurs = "0" maxOccurs = "unbounded"/>
                    <xs:element name = "passengerPlane" type = "passengerPlane" minOccurs = "0" maxOccurs = "unbounded"/>
                    <xs:element name = "militaryPlane" type = "militaryPlane" minOccurs = "0" maxOccurs = "unbounded"/>
                </xs:sequence>
                <xs:attribute name = "name"/>
            </xs:complexType>
        </xs:element>

    <xs:complexType name = "plane">
            <xs:sequence>
                <xs:element name = "name"/>
                <xs:element name = "cruisingSpeed"/>
                <xs:element name = "flightRange"/>
                <xs:element name = "maxTakeOfWeight"/>
                <xs:element name = "maxFlightHeight"/>
                <xs:element name = "fuelConsumption"/>
            </xs:sequence>
    </xs:complexType>

    <xs:complexType name = "cargoPlane">
        <xs:complexContent>
            <xs:extension base = "plane">
                <xs:attribute name = "overSeasFlight" type = "xs:boolean" use="required"/>
            </xs:extension>
        </xs:complexContent>

    </xs:complexType>

    <xs:complexType name = "passengerPlane">
        <xs:complexContent>
            <xs:extension base = "plane">
                <xs:attribute name = "passengersQuantity" type = "xs:int" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name = "militaryPlane">
        <xs:complexContent>
            <xs:extension base = "plane">
                <xs:attribute name = "WeaponType" type="WeaponType" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name = "WeaponType">
        <xs:restriction base = "xs:string">
            <xs:enumeration value = "Machinegun"/>
            <xs:enumeration value = "Laser"/>
            <xs:enumeration value = "Rockets"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== iggor1995/Airlines/src/main/java/xmlpack/airlines.xml
<?xml version="1.0"?>

<aircompany
        xmlns="https://www.w3schools.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://www.w3schools.com xml.xsd">
        <cargoPlane overSeasFlight="true">
            <name>Boeing - 747 - 8</name>
            <cruisingSpeed>900</cruisingSpeed>
            <flightRange>10500</flightRange>
            <maxTakeOfWeight>447</maxTakeOfWeight>
            <maxFlightHeight>13750</maxFlightHeight>
            <fuelConsumption>10300</fuelConsumption>
        </cargoPlane>
        <passengerPlane passengersQuantity="180">
            <name>Tupolev TU - 154</name>
            <cruisingSpeed>950</cruisingSpeed>
            <flightRange>5200</flightRange>
            <maxTakeOfWeight>300</maxTakeOfWeight>
            <maxFlightHeight>11000</maxFlightHeight>
            <fuelConsumption>6200</fuelConsumption>
        </passengerPlane>
        <passengerPlane passengersQuantity="192">
            <name>Tupolev TU - 204</name>
            <cruisingSpeed>850</cruisingSpeed>
            <flightRange>40000</flightRange>
            <maxTakeOfWeight>107</maxTakeOfWeight>
            <maxFlightHeight>7200</maxFlightHeight>
            <fuelConsumption>3450</fuelConsumption>
        </passengerPlane>
        <passengerPlane passengersQuantity = "95">
            <name>Sukhoi SuperJet - 100</name>
            <cruisingSpeed>900</cruisingSpeed>
            <flightRange>4500</flightRange>
            <maxTakeOfWeight>42</maxTakeOfWeight>
            <maxFlightHeight>8000</maxFlightHeight>
            <fuelConsumption>1700</fuelConsumption>
        </passengerPlane>
        <militaryPlane WeaponType="Rockets">
            <name>Douglas F-4 Phantom II</name>
            <cruisingSpeed>2500</cruisingSpeed>
            <flightRange>2300</flightRange>
            <maxTakeOfWeight>10</maxTakeOfWeight>
            <maxFlightHeight>17000</maxFlightHeight>
            <fuelConsumption>4000</fuelConsumption>
        </militaryPlane>

</aircompany>
